### ISSUE TITLE
Random KP

### ISSUE THREAD

**Issue by tarkh** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#1]
Hi, markkpa! Thanx for your setup!
I have the same rig:
MB: Huananzhi X99 F8D
CPU: 2x Xeon E5 2678 V3

I've flashed my bios with your file and used your EFI to boot macOS Mojave (I'm working with sound, so staying with full 32 bit support is my goal on this workstation). So everything seems to work fine, but sometimes I'm catching freezes (KP). There are no permanent data in backtrace for them, so I can't connect them with any specific software or kext. But in general it is CPU related:

`mp_kdp_enter() timed-out on cpu... NMI pending on cpus... timed-out during locked wait after NMI...`

Then while do trial and errors process I've figured, that possibly this behaviour caused by CPU temp and frequency measurement software. I've tried 2 different tools: iStat menu and HWMonitorSMC2. It's not 100% because I don't have enough data to make conclusions yet.

Can you please test this tools or give advice on how to measure CPU temps and frequency on this rig? Maybe we need to tweak Opencore config somehow to properly set up two socket system? Or do a proper ACPI setup?

Thank you!

**Comment by tarkh** [comment]
Ok, seems the problem not related to the CPU measuring software. I've tried to flashback default bios without turbo unlock and now everything works just fine. So I'm curious - is there any CPU UNDERVOLTING modifications in the bios, provided in this repo? If so it's highly possible, that random KPs in my case was caused by insufficient voltage. It's just a theory, next week I'll try to patch bios myself and do turbo unlock without EFI file (S3TurboTool). Will report.

**Comment by markkpa** [comment]
Yes, the V3.EFI (DXE driver) in the Driver folder sets the undervolting values.  You can use your own DXE driver instead of mine.  The bios does NOT contain any undervolting values (it only deletes the microcode required for turbo boost unlock).  I just updated to OpenCore 0.6.7 which includes a new CtlnaAHCIPort.kext for Catalina and Big Sur.  The new kext may solve the freezing issues.  You may want to update to this new setup.

**Comment by markkpa** [comment]
Yes, the V3.EFI (DXE driver) in the Driver folder sets the undervolting
values. You can use your own DXE driver instead of mine. The bios does NOT
contain any undervolting values (it only deletes the microcode required for
turbo boost unlock). I just updated to OpenCore 0.6.7 which includes a new
CtlnaAHCIPort.kext for Catalina and Big Sur. The new kext may solve the
freezing issues. You may want to update to this new setup.

**Comment by tarkh** [comment]
Thanks! I've fixed my freeze issue by using custom VoodooTSCSync.kext with hardcoded number of threads (47) in it's info plist. Also I flashed another bios from [this repo](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/tree/master/Huananzhi%20X99-F8D/2020-06-24). Custom bios is **HNX99F8D_200624_kot_v002.zip**. This bios also contains some altered ME regions in it, so it needs to be flashed by bios Programmer, not Afudos, so I use CH341A with clip. Good thing is this bios have full unlock on future re-flashing, so no need to use Programmer in future. Also I manually patched all ACPI stuff following Opencore guides, everything went smoothly and now I've got pretty stable system. I'll post my repo after weekends. Still did not do turbo unlock and undervaluing stuff, this is stage #2 of my work, will try it next week.

The main question still - is it possible to set up sleep on this hardware? Have you any progress with that? Even with all ACPI patched and USB stuff properly arranged I can't make it works - when rig goes to sleep it will KP on wake and restart...

**Comment by markkpa** [comment]
Another member has posted patches for power management for this motherboard - I haven't tested it yet, but you may want to give it a look.

**Comment by markkpa** [comment]
Now included several modifications for better power management.

**Comment by markkpa** [comment]
I'm closing now that I can avoid crashing from black screen.  This requires checking Prevent computer from sleeping automatically when the display is off in Evergy Saver system preferences.  Not everything I wanted but at least I no longer crash.
