### ISSUE TITLE
macOS Monterey 12.3 cannot boot and install normally

### ISSUE THREAD

**Issue by itq5** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#10]
After seeing your project, I bought a piece of huanan x99 f8d, using the CPU of E5 2696v3, and brushed 9.0 according to the tutorial X99f8dna in bat After ROM and bios are configured, the boot OC will report the following errors. Can you help me check whether it is my setting problem or does not support this version?
![1649525616(1)](https://user-images.githubusercontent.com/42521985/162585536-74580ced-cce9-4b60-a82e-19f6e2020fd8.png)
![1649525667](https://user-images.githubusercontent.com/42521985/162585569-3da762af-7d66-4797-a581-e82a15502d51.png)
![1649525756(1)](https://user-images.githubusercontent.com/42521985/162585629-cdc0f889-037a-40a8-ac4b-b5f4f2e42598.png)

**Comment by markkpa** [comment]
1) I did make a few changes in my bios setting which can now be viewed on photos 080.jpeg and 142.jpeg.  I have uploaded the new photo set under Bios_Settings.zip. Please check it.
2) I don't know which graphic card you are using - therefore, you can try deleting AGPMInjector.kext from folder EFI/OC/Kexts/AGPMInjector.kext - see if it will boot without this kext.

**Comment by seven2800** [comment]
Have you succeeded now? I'm stuck on the Acpicpu100

**Comment by itq5** [comment]
### When I reinstall, the OC boot cannot see the installation

**Comment by itq5** [comment]
> 1. 我确实在我的bios设置中做了一些更改，现在可以在照片080.jpeg和142.jpeg上查看。我已将新照片集上传到Bios_Settings.zip。请检查它。
> 2. 我不知道您使用的是哪种图形卡 - 因此，您可以尝试从文件夹EFI / OC / Kexts/中删除AGPMInjector.kext - 看看它是否会在没有此kext的情况下启动。



> 你现在成功了吗？我被困在 Acpicpu100 上

When I reinstall, the installation disk cannot be seen during OC boot

**Comment by markkpa** [comment]
OK, I have reverted back to my previous EFI from one month earlier - please try it.  I've just uploaded now.
Also, I made one additional change to bios settings on photo 010.jpeg

**Comment by seven2800** [comment]
I can install it, but I can't open the hyperthreading. If I open it, will get stuck in acpicpu
![image](https://user-images.githubusercontent.com/42139398/162625527-bff8bf0c-ceff-4511-8dcf-abf58c8407cf.png)

**Comment by markkpa** [comment]
Will it open with hyper-threading disabled?  By the way, the overall system performs faster with hyper threading disabled because the single thread performance is boosted.  Also, it is more secure with hyper-threading disabled.  Intel has several security vulnerabilities due to hyper threading.

**Comment by seven2800** [comment]
> 

If I turn off hyperthreading, The system is normal, but when i open hyperthreading  ,will unable to enter the system,
display the above error

**Comment by seven2800** [comment]
my CPU of E5 2696v3  ,My friend can successfullyopen hyperthreading using other CPU,I don't know if the reason is CPU

**Comment by markkpa** [comment]
Did you start all over again from the beginning using the previous EFI I just uploaded?  If not, I would suggest you start the entire installation all over again from the beginning - it may work.  Other users are definitely using E5-2696v3 CPU's - in fact, the last bios I posted was optimized for E5-2696v3.

**Comment by markkpa** [comment]
OK, sorry - ignore my last post.  Reinstalling will not a make a difference.  With hyperthreading enabled, your CPU's need more power.  So, the modified bios has too much undervolting for your CPU's.  For other E5-2696v3's it works just fine.  It all depends on the efficiency of your specific CPU's.

**Comment by itq5** [comment]
After using the efi file and adding rom, sn and other information, I use 12.1's own 12.3 file, stuck in the following steps, do you have a processing method? 
![Screenshot_2022-04-11-01-10-26-373_com miui gallery](https://user-images.githubusercontent.com/42521985/162631198-656a94e5-4d1e-43a6-823b-dba70281cb27.png)

**Comment by markkpa** [comment]
I am only guessing, it may have something to do with the settings changed in photo 080.jpeg - it seems macOS doesn’t like it when these are changed.  After I had a similar problem; I no longer change these settings.  Somehow I was able to reboot after a few times.  Sorry, I guess I don’t know how to help.

**Comment by seven2800** [comment]
> OK, sorry - ignore my last post. Reinstalling will not a make a difference. With hyperthreading enabled, your CPU's need more power. So, the modified bios has too much undervolting for your CPU's. For other E5-2696v3's it works just fine. It all depends on the efficiency of your specific CPU's.

Do you mean I need more power?

**Comment by seven2800** [comment]
> OK, sorry - ignore my last post. Reinstalling will not a make a difference. With hyperthreading enabled, your CPU's need more power. So, the modified bios has too much undervolting for your CPU's. For other E5-2696v3's it works just fine. It all depends on the efficiency of your specific CPU's.

The power supply I use now is 750W, and the graphics card is amd 460

**Comment by markkpa** [comment]
The issue is not your power supply.  Instead, the modified bios is "undervolted" which tricks the CPU to using higher frequency (turbo boost).  The newest x99f8dNa.rom bios is using, -65mv, -60 cache, -60 sys agent.  Perhaps you need -65mv, -50 cache, -50 sys agent to be stable.  Or perhaps -50mv, -50 cache, -50 sys agent.  It's trial and error.  You have use the bios tools from the Russian guy (link is listed at the bottom) change these settings.  See closed issue 2696 v3 Instability #8 - mosberg12 made the latest bios which I posted to the site.

**Comment by seven2800** [comment]
> The issue is not your power supply. Instead, the modified bios is "undervolted" which tricks the CPU to using higher frequency (turbo boost). The newest x99f8dNa.rom bios is using, -65mv, -60 cache, -60 sys agent. Perhaps you need -65mv, -50 cache, -50 sys agent to be stable. Or perhaps -50mv, -50 cache, -50 sys agent. It's trial and error. You have to use the bios tools from the Russian guy (link is listed at the bottom) and change these settings. See closed issue 2696 v3 Instability #8 - mosberg12 made the latest bios which I posted to the site.

Thank you very much for your enthusiastic answer. I'll try

**Comment by seven2800** [comment]
> The issue is not your power supply. Instead, the modified bios is "undervolted" which tricks the CPU to using higher frequency (turbo boost). The newest x99f8dNa.rom bios is using, -65mv, -60 cache, -60 sys agent. Perhaps you need -65mv, -50 cache, -50 sys agent to be stable. Or perhaps -50mv, -50 cache, -50 sys agent. It's trial and error. You have to use the bios tools from the Russian guy (link is listed at the bottom) and change these settings. See closed issue 2696 v3 Instability #8 - mosberg12 made the latest bios which I posted to the site.

I try again 0mv, 0 cache, 0 sys agent ,  but still not successful I don't know what is the problem

**Comment by seven2800** [comment]
> 

I think it may be the reason for the OC setting

https://github.com/tarkh/hackintosh/tree/main/Huananzhi-F8D#-version-for-macos-11-big-sur

If your processor differs from E5 2678v3, you will need to reconfigure VoodooTSCSync.kext as it is configured for 48 threads. You can [use the configurator](https://www.insanelymac.com/forum/files/file/744-voodootscsync-configurator/), which will help generate the necessary file. Or you can try to correct the number of threads manually in the kext config EFI/OC/Kexts/VoodooTSCSync.kext/Contents/Info.plist in the key IOKitPersonalities > VoodooTSCSync > IOPropertyMatch > IOCPUNumber you need to put the total number of threads of your processors starting from 0. I.e. for two E5 2678v3 (12 x 2 x 2), the current value is 47.

Unfortunately, I'm not very good at configuring OC. I think the general problem should be here

**Comment by markkpa** [comment]
I don't use VoodooTSCSync.kext.  Instead, I use CpuTscSync.kext.  I believe you should one or the other but not both.

**Comment by markkpa** [comment]
There is nothing I can do to help.  These screens are rarely helpful - they tell you almost nothing about the true cause of the problem.

**Comment by itq5** [comment]
My steps: 
1. After brushing the x99f8dNa.rom bios file, I set the bios according to the bios settings, and found that some locations did not provide screenshots. 2. After 2. I downloaded the EFI file to the local area, I modified the Serial Member, MLB, SMUUID & ROM And add a log print in the config.plist file with OC Auxiliary Tools and saved the configuration 
3. After copying to the USB flash drive, use F7. After the USB drive starts up, load the 12.1 system card master and print at the Disk3 IO / Error location 
4. My motherboard is an F8D motherboard, the CPU is an E5 2696v3, and the graphics card is an XFX RX590 graphics card 


Can you provide a screenshot of all the current configuration pages of your computer's latest bios, efi files on your latest computer, thank you. 

![Screenshot_2022-04-12-02-26-22-298_com miui gallery](https://user-images.githubusercontent.com/42521985/162805131-61c3f5d4-da8f-42f3-950b-2c0dcc954546.png)
![Screenshot_2022-04-12-02-26-15-122_com miui gallery](https://user-images.githubusercontent.com/42521985/162805187-1570823a-c31c-49e0-abff-85ba7ed96a16.png)

**Comment by itq5** [comment]
> 

My email address is root@itq5.com, thank you for sharing. 
Also, have you swiped the bios x99f8dna.rom in the library? Can I compare all the screenshots of the configuration in bios? Thank you for your support

**Comment by seven2800** [comment]
> 

Thank you very much. According to your settings, I solved the problem that the hyper thread cannot be turned on

**Comment by markkpa** [comment]
Sounds good.  I'm glad you were able to complete the install. I didn't know about the core limit in macOS either.  Happy computing!
