### ISSUE TITLE
I have the latest 2022 BIOS of Huanan x99-f8d here. Can I optimize it based on this BIOS

### ISSUE THREAD

**Issue by itq5** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#11]
I have the latest 2022 BIOS of Huanan x99-f8d here. Can I optimize it based on this BIOS
[AmericanMegatrendsInc.-5.11.zip](https://github.com/markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh/files/8457510/AmericanMegatrendsInc.-5.11.zip)

**Comment by markkpa** [comment]
You would need to use my version of the bios if you want to benefit from Turbo Boost unlocked - it represents a significant increase in performance.
