### ISSUE TITLE
bigsur 11.3.1 

### ISSUE THREAD

**Issue by kulanchong** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#2]
mp_kdp_enter() timed-out on cpu 1, NMI-ing
mp_kdp_enter() NMI pending on cpus: 0 3
mp_kdp_enter() timed-out during locked wait after NMI;expected 24 acks but received 23 after 37960295 loops in 1299999960 ticks
panic(cpu 1 caller 0xffffff801039e081): "IPI timeout, unresponsive CPU bitmap: 0x8, NMIPI acks: 0x0, now: 0x0, deadline: 38148261500319, pre-NMIPI time: 0x22b2159356db, current: 0x22b23360bed0, global: 0"@/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.101.2/osfmk/x86_64/pmap.c:2892
Backtrace (CPU 1), Frame : Return Address
0xffffffa285383880 : 0xffffff801028e02d mach_kernel : _handle_debugger_trap + 0x3fd
0xffffffa2853838d0 : 0xffffff80103d48e3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffa285383910 : 0xffffff80103c4eda mach_kernel : _kernel_trap + 0x55a
0xffffffa285383960 : 0xffffff8010232a2f mach_kernel : _return_from_trap + 0xff
0xffffffa285383980 : 0xffffff801028d84d mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffa285383aa0 : 0xffffff801028db43 mach_kernel : _panic_trap_to_debugger + 0x273
0xffffffa285383b10 : 0xffffff8010a9d68a mach_kernel : _panic + 0x54
0xffffffa285383b80 : 0xffffff801039e081 mach_kernel : _pmap_flush_tlbs + 0x7d1
0xffffffa285383c40 : 0xffffff80103a40cc mach_kernel : _pmap_remove_range + 0x37c
0xffffffa285383d20 : 0xffffff80103a4eb6 mach_kernel : _pmap_remove_options + 0x1f6
0xffffffa285383d80 : 0xffffff8010333145 mach_kernel : _vm_map_remove + 0x725
0xffffffa285383ed0 : 0xffffff8010332a93 mach_kernel : _vm_map_remove + 0x73
0xffffffa285383f00 : 0xffffff80135d394d com.apple.kec.pthread : __bsdthread_terminate + 0xa4
0xffffffa285383f40 : 0xffffff8010940dae mach_kernel : _unix_syscall64 + 0x2ce
0xffffffa285383fa0 : 0xffffff80102331f6 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.kec.pthread(1.0)[4AE08904-B706-3DD5-9E70-C4907582B3A3]@0xffffff80135d2000->0xffffff80135dafff

Process name corresponding to current thread: WindowServer
Boot args: keepsyms=1 npci=0x2000 swd_panic=1

Mac OS version:
20E241

Kernel version:
Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
Kernel UUID: 068F99A3-1DB3-31C0-87D5-09942F122BB6
KernelCache slide: 0x0000000010000000
KernelCache base:  0xffffff8010200000
Kernel slide:      0x0000000010010000
Kernel text base:  0xffffff8010210000
__HIB  text base: 0xffffff8010100000
System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)
System shutdown begun: NO
Panic diags file available: NO (0xe00002bc)
Hibernation exit count: 0

System uptime in nanoseconds: 38149761941738
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000022b26f024408
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x000000246343c448 0x0000000000000000

**Comment by markkpa** [comment]
Are you using my USBPorts.kext (these are my USB mappings).  Otherwise, you need to delete my USBPorts.kext and instead use USBInjectAll.kext with XhciPortLimit set to True.  You may want to try slide=128 in boot args.  And, are you using all of the files in the ACPI folder and Kext folders?  This setup depends on all the files being used.  Obviously, if your GPU is not RX570 then you need to alter AGPMInjector.kext (or remove it).  I use this tool which is helpful:  https://github.com/Pavo-IM/OC-Gen-X/releases 
Also, if you are not using NVMe then remove NVMeFix.kext.

**Comment by kulanchong** [comment]
x99-f8d,e5-2690 v3,mis rx570 4g,128g ram,1t nvme,EFI changes SMBIOS only
Thank you very much for your EFI. My English is not very good. Sorry

**Comment by markkpa** [comment]
I uploaded a new EFI yesterday along with update bios setting photos.  Is your problem resolved?  Or, should I keep this issue open?

**Comment by kulanchong** [comment]
I'll test it right away. Thank you very much
