### ISSUE TITLE
10.13.6 high sierra

### ISSUE THREAD

**Issue by svobodin** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#3]
Hey! opencore cannot boot the installed system. Big Sur loads fine, but unfortunately I have 1080 ti and the loading stops at the beginning. And the second question: why don't you use the dxe BIOS driver (S3TurboTool) instead of the efi method for turbo boost all cores?

**Comment by markkpa** [comment]
If your GPU is not AMD RX570 then you need to alter AGPMInjector.kext (or remove it). I use this tool which is helpful: https://github.com/Pavo-IM/OC-Gen-X/releases

I've tried several times to use S3TurboTool without success.  For some reason, it does not work for Huananzhi Dual CPU boards - Miyconst on YouTube has confirmed this.  If you find a way that woks, please let me know.

**Comment by markkpa** [comment]
If you are not installing Big Sur 11.3 or newer, I think you will have to modify config.plist under Kernel Emulate to use a different Cpuid1Data & Cpuid1Mark for Haswell E:

Cpuid1Data: C3060300 00000000 00000000 00000000
Cpuid1Mask: FFFFFFFF 00000000 00000000 00000000

Also remove all Kernal Patches from config.plist

**Comment by svobodin** [comment]
> If your GPU is not AMD RX570 then you need to alter AGPMInjector.kext (or remove it). I use this tool which is helpful: https://github.com/Pavo-IM/OC-Gen-X/releases
> 
> I've tried several times to use S3TurboTool without success. For some reason, it does not work for Huananzhi Dual CPU boards 

You can try my version of your bios. -75mv, -50 cache, -50 sys agent - all ok. dual 2678v3

[x99f8dK_new.zip](https://github.com/markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh/files/6648672/x99f8dK_new.zip)

**Comment by markkpa** [comment]
Thanks.  By, the way, the newer "L" version of the bios I uploaded last week has additional overclock features in the bios - likely intended for unlocked CPU's; I'm not sure.

**Comment by markkpa** [comment]
Hey, can you read Issue #4 Unstable Vcore?  Do you have any suggestions?  Thanks.

**Comment by markkpa** [comment]
Done

**Comment by markkpa** [comment]
Hello.  I hope all is well.  I wanted to update the X99-F8D bios using the latest published on Github; however it does include the undervolt settings.  I was not successful using the S3 Turbo Tool to apply the undervolt.  Did you use the PEI or DXE function to generate the ffs output for dual CPU?  And what tool did you use to flash the bios with the new file?  Does it matter if it is .bin or .rom format?

 Did you use https://github.com/Koshak1013/HuananzhiX99_BIOS_mods#Instructions-for-unlocking-the-maximum-frequency-for-all-cores-not-two-unlock

Thanks for your help!

**Comment by markkpa** [comment]
One more question.  Did you change any other bios settings besides PEI/DXE undervoltages?  It seems you had boosted performance from other settings as well?
