### ISSUE TITLE
Unstable Vcore

### ISSUE THREAD

**Issue by kalentjne** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#4]
Hi - I used your modded bios on X99 F8D with dual E5 2678v3. System seems a bit unstable.
How do you get the ffs driver? Can I somehow get an instruction on generating it so I can test different offset?
Thanks!

**Comment by markkpa** [comment]
I can offer a couple of suggestions.  1) this is the ffs I was using prior to the latest update (it might be more stable for you): https://github.com/freecableguy/v3x4/releases/download/v3x4-0.10b-i306f2-rc9/v3x4-0.10b-i306f2-rc9_90_70_50.efi
2) Several more options are listed here:  https://github.com/freecableguy/v3x4/releases/tag/v3x4-0.10b-i306f2-rc9

**Comment by kalentjne** [comment]
Wew I figured out how to change the FFS offsets myself just couple hours ago and successfully flash my 2 systems.
Asus Z10PA-D8C and Huananzi X99 F8D, both with dual E5 2678v3. My systems are under stress testing to find the proper Voltage Offsets.

So I tried to use your BIOS and used UEFI tool to see its contents, found out that the FFS was actually made by "ser8989", a Russian Developer.
So I continue to dig in a bit and found his Github, there he posted a tool called S3TurboHack (latest 1.53). In his tool, there is a GUI ffs builder that you can use to alter the offset value and unlock Turbo Boosts all core. His guide was originally made for Huananzhi mainboard but I also managed to apply the same ffs for my Z10PA-D8C bios, just different method and software version to flash since the BIOS is manufacturer locked. Now 2 systems are now both unlocked.
My systems are under Windows10 21h1 and flashing the BIOS is everything I need to do to get the Turbo unlocked.

Credits:
https://xeon-e5450.ru/socket-2011-3/e5-2600-v3/dobavlyaem-anlok-v-bios-raz-i-navsegda-cherez-s3turbotool/
https://www.win-raid.com/t455f16-Guide-How-to-flash-a-modded-AMI-UEFI-BIOS.html?fbclid=IwAR0sbRk1Uzho3qONxFzMaMvdYDcgjPsbdTOmvg-UEITKgDJU4XP9QyG4_JU
https://github.com/Koshak1013/HuananzhiX99_BIOS_mods#Instructions-for-unlocking-the-maximum-frequency-for-all-cores-not-two-unlock (ser8989's repository)
