### ISSUE TITLE
Question: How  to install a Thunderbolt 3 GC_Titan_Ridge - Card in a Huananzhi F8D? 

### ISSUE THREAD

**Issue by dreader27** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#5]
Hallo, thanks for the installations files. I have updated to OC 0.7.2 and running Monterey beta 5. 
Now i try to install a titan ridge card.  The firmware is updated and i can see the card in the systemproperties. 
But i am not able to start hotplugging...
Maybe you know some links with tips/advice? 
Greetings and thanks!
Heiner

**Comment by markkpa** [comment]
I don't have experience with Thunderbolt as I am using usb 3.1 pci-e card.  However, I would suggest watching this video which describes how to update Opencore AND Thunderbolt using an online resource called hackindrom - links below:
https://www.youtube.com/watch?v=myt51UjN5h0
https://hackindrom.zapto.org

Good luck!

**Comment by markkpa** [comment]
If you are using the Titan Ridge motherboard, then hackindrom website might help.  But if you are trying to install Titan Ridge Thunderbolt card onto the Huananzhi motherboard, then maybe it won't be that helpful.  Best of luck.

**Comment by markkpa** [comment]
I just uploaded my OC 0.7.2 EFI - FYI

**Comment by dreader27** [comment]
Ok, thanks for the links. Yes, i´m using a flashed Titan Ridge and  i try the "hackindrom" way.  Also i found this site and followed the guides: 
https://elitemacx86.com/forums/thunderbolt.131/

I will try your EFI0.7.2 with Monterey b5.

**Comment by dreader27** [comment]
FYI :  i connected my firewire audio device (Saffire pro 24 dsp) with a adapter firewire to thunderbolt (and thunderbolt 3 to2)  ...and it is working.
Does that mean, the thunderbolt card is installed correct?
![Bildschirmfoto 2021-08-18 um 17 30 41](https://user-images.githubusercontent.com/53608282/129927623-19f7f265-c491-48e2-b04e-61eb94baebbb.png)
![Bildschirmfoto 2021-08-18 um 17 31 05](https://user-images.githubusercontent.com/53608282/129927697-4a30477b-41ee-4a9e-99f7-5605b040264d.png)

**Comment by markkpa** [comment]
When I compare it to my Macbook Pro, it looks correct.
<img width="656" alt="Screen Shot 2021-08-18 at 11 51 34 AM" src="https://user-images.githubusercontent.com/40475192/129931354-04cb1b3f-cb69-452a-957d-bb136e42b4d5.png">

**Comment by 2ndmehmet** [comment]
How did you connect the thunderbolt header to motherboard?

**Comment by markkpa** [comment]
I did not connect a Thunderbolt 3 card to my motherboard.  But, I believe dreaded27 did:  https://github.com/markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh/issues/5#issuecomment-901096229 <https://github.com/markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh/issues/5#issuecomment-901096229>

**Comment by 2ndmehmet** [comment]
@dreader27 Can you help?

**Comment by dreader27** [comment]
Hi, you don' t need to connect the tb3 card to the board.  You need a flashed  Titan Ridge Card.
Follow this guides:
https://elitemacx86.com/forums/thunderbolt-and-firewire.131/
https://www.tonymacx86.com/threads/thunderbolt-3-modified-firmware-custom-ssdt-discussion.293279/
and in german language ( google translater may help):
https://www.hackintosh-forum.de/forum/thread/46713-natives-thunderbolt3-an-jedem-rechner/

Heiner




________________________________

**Comment by 2ndmehmet** [comment]
@dreader27 Is hot plug working?

**Comment by dreader27** [comment]
With my configuration: no.
I have to restart onetime and my firewire audio device is working.
Here is my configuratio:
https://www.hackintosh-forum.de/forum/thread/54117-huananzhi-x99-f8d-dual-lga-2011-3/

Heiner

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
