### ISSUE TITLE
[Question] Compatibility with Monterey OS Beta

### ISSUE THREAD

**Issue by noteMASTER11** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#6]
Hello! Thank you for your work.
As I can see in the attachments the only Big Sur was confirmed with your bootloader.

I have F8D with 2678v3*2 and R9 290X. Everything work pretty good on my Big Sur 11.6. But times goes by and we need to upgrade soon if we wanna stay with the latest versions of software.

Could you tell me please have you ever tested your OC with Monterey? Thank you.

**Comment by markkpa** [comment]
Yes, I am using the exact same configuration for Monterey Preview - it works just fine.

**Comment by noteMASTER11** [comment]
Unfortunately I've got random reboots while trying to install Monterey Beta 6 update. The halt is random and very quick, I can't catch the screen photo.
Please Tlg me to @mkzxt if it's possible for you. I can show what did I do to boot up. Of course I've set iMac Pro 1.1 and generated custom serial number. But it doesn't help on my configuration.

I have another OC based on https://github.com/tarkh/hackintosh/tree/main/Huananzhi-F8D and it boots up a bit better than your one. But I have "No port micro restart ( we don't support SMC on this platform)". The main thing I've changed to boot without KP is VoodooTscSyck > CPUTscSync.

**Comment by markkpa** [comment]
OK, you're right.  I updated the EFI today (just in case I made some changes - not sure - it may be the same as before).  The EFI has securebootmode set to Disabled.  However, after the initial install, if you are caught in continuous reboot loop, then change securebootmode to x86legacy.  Then you can boot into the new install normally.
