### ISSUE TITLE
New Bios F8D ? 

### ISSUE THREAD

**Issue by dreader27** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#7]
I saw on http://www.huananzhi.com/html/1//184/185/491.html?view=drivers#anchor a Bios for the F8D Board named: 
X99-F8DV2.3 出货BIOS 21-9-15 华南
Does it mean it is dated on 15.09.2021 ?
Maybe it has some advantages? 
By the way: is TPM  impossible for the F8D? 
Thanks for your work (EFI)!
I installed monterey beta 9 now.

Heiner

**Comment by andvalb** [comment]
Checked jtpm connector pinout on the f8d mobo with the oscilloscope and found that they miss-route this connector IMHO.
Some adapter will be needed.
![image](https://user-images.githubusercontent.com/43944259/139542327-58307714-ae56-44d8-bd94-0dcb45fbc193.png)

**Comment by markkpa** [comment]
Thanks for your insight.  Let me know if you ever find a solution.  Thanks again.

**Comment by markkpa** [comment]
I was to update and post the latest bios which also includes turbo boost unlock.  DONE!

**Comment by lucasfcnunes** [comment]
@markkpa, about the TPM compatibility. Did you get it to work with windows 11 (on HUANANZHI X99-F8D)?

**Comment by SlimRG** [comment]
I have the same question about tpm

**Comment by mehmetaydogduu** [comment]
> Checked jtpm connector pinout on the f8d mobo with the oscilloscope and found that they miss-route this connector IMHO. Some adapter will be needed. 

TPM 2.0 is a forced requirement novadays. Do you still have oscilloscope and the the mobo? The diagram you draw is similar to msi 14 pin lpc. There is a diagram for it. https://tr.aliexpress.com/item/1005004048395590.html

**Comment by lucasfcnunes** [comment]
They have two MBs HUANANZHI X99-F8D and HUANANZHI X99-F8D PLUS. None of them work with TPM ^2.0?
