### ISSUE TITLE
2696 v3 Instability

### ISSUE THREAD

**Issue by mosberg12** [markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh#8]
Good afternoon, first & foremost great work on these bios!  The bios works great on a x99 t8d 2678 v3 system!

However, I also have one f8d with dual 2696v3's & one t8d with dual 2696v3's.  I believe the voltage offsets are causing instability.

The instabilities seems to arise when under "moderate load" Full load fine, idle fine somewhere in-between complete system hang or crash (sporadically but same behavior on f8d & t8d (not with the 2678's))

Would it be possible for you to easily create a bios without the offsets? & with the overclock "offsets" working in bios?  It seems the offsets in bios have no effect due to the existing voltage overrides.

**Comment by windystrife** [comment]
-65mv, -50 cache, -50 sys agent is more stable, i can send u my BIOS, btw if u want to use Hackintosh, u should disable 2 cores 4 threads in every socket? after that, actually u will have 32 cores, 64 threads hackintosh 👯 
Clang in geekbench5 is nearly the same with M1 Ultra LOL

**Comment by mosberg12** [comment]
Thanks for the reply windystrife.. I ended up generating a bios through the same s3turbo tool methods.. stress testing -60m, -60mv, -60mv now on the 2696v3 rigs... so far so good

Also noticed the x99f8dN.rom bios is missing the under-volting on CPU 2.  There is still 1 CPU's performance left on the table!

![turbo](https://user-images.githubusercontent.com/101213169/157471980-a5657d8f-efca-4e23-9110-6b4119879056.png)

Haha & that's awesome! these chips scream after lifting the restrictions.. Pretty awesome to tie M1 Ultra for a few hundred bucks!

Have you had any luck with fivr bug? can't seem to get it to make any difference to the frequency's

**Comment by markkpa** [comment]
If you send me your modified bios, I would be glad to post it on the site for others.

**Comment by mosberg12** [comment]
[2696v3dual.zip](https://github.com/markkpa/x99-t8d-and-x99-f8d-Opencore-Hackintosh/files/8216661/2696v3dual.zip)

Here it is, I am still stress testing.  However it has so far been stable for 3hrs

**Comment by markkpa** [comment]
Does the testing remain stable?  Or, do you want to consider -65mv, -50 cache, -50 sys agent as windystrife suggested before I post?  Also, my standard bios does have both CPU's unlocked including CPU2:
![biosALLcores](https://user-images.githubusercontent.com/40475192/157870231-ff6907f6-e6c3-4697-9f8d-e4805f7c60af.JPG)

**Comment by mosberg12** [comment]
It remained stable on t8d & f8d equipped with 2696 v3 stress testing for > 24 hrs.  I ultimately stopped the tests after deeming the servers stable for use.

2696v3 speeds under load 
![image](https://user-images.githubusercontent.com/101213169/157889573-60bbe632-bb74-4226-aab7-69a9215a959b.png)


I never validated the voltage on the previous bios.. However I had a strange behavior which one cpu would reach max tdp @ ~200mhz less than the other cpu under load

**Comment by windystrife** [comment]
Do u need BIOS file anymore @markkpa, i deleted it, but can recreate it, on my side it is stable
tried @mosberg12 's BIOS, it is stable too

**Comment by markkpa** [comment]
Great!  Thank you both for your support.  I will publish this as an alternative bios which is more stable if you have more cores than E5-2678v3.  Windystrife does not need to recreate the other bios.  Thanks!

**Comment by markkpa** [comment]
Thanks again for your help.  The new bios (x99f8dNa.rom) appears to work well for E5-2678v3.  No need to maintain both.  I'm not as good at generating bios updates as you guys.  I will try to stay in touch the next time a new version is released from Huananzhi.

**Comment by seven2800** [comment]
> -65mv, -50 cache, -50 sys agent is more stable for 2696v3, i also have dual 2696v3, i can send u my BIOS, btw if u want to use Hackintosh, u should disable 2 cores 4 threads in every socket in BIOS. After that, actually u will have 32 cores, 64 threads hackintosh 👯

Why do you say thatdisable hyper threading, you will have 32 core 64 threads hackintosh?

**Comment by markkpa** [comment]
If you disable hyper threading you will have 36 cores (18 cores + 18 cores = 36 cores).  I never use hyper threading because everything runs slower with hyper threading enabled.  Hyper threading will split one true core into 2 virtual cores.  However, one true core is always much faster than virtual cores.  Since you have 36 true cores - that should be more than enough for your work.  Hyper threading always makes the CPU less stable - you need to feed more voltage to the CPU to stabilize hyper threading - but this bios is not giving you enough voltage for your CPU.  The simple solution is to disable hyper threading.  Everything will run faster and will be more stable.

**Comment by mosberg12** [comment]
This is inaccurate.  In the vast majority of cases Hyperthreading improves performance.  Hyperthreading allows unutilized portions of a processor core to be utilized while the primary thread is idle (accessing data from ram for example).  In the few cases it does detriment performance you can use numactl (if you're a Linux user) to pin the process to cores.

Compare a Passmark benchmark with HT off and then with it on & you will see a massive difference.

Core utilization example:
![image](https://user-images.githubusercontent.com/101213169/162801426-fd777baf-e644-4579-8609-f75d7c7ae6c1.png)
